### ISSUE TITLE
Camera does not save photo

### ISSUE THREAD

**Issue by maverick74** [tfonteyn/NeverTooManyBooks#11] opened 2023-05-16 19:46 UTC
If I choose to take a photo (from camera) of my book cover, it does not load the photo into the field and never saves it.

![Screenshot_2023-05-16-20-32-49-352_com hardbacknutter nevertoomanybooks](https://github.com/tfonteyn/NeverTooManyBooks/assets/14912461/ca8fc3b1-fb9d-409c-87f4-26dd2b1692f0)

**Comment by tfonteyn** [comment] 2023-05-16 22:00
This sounds like a strange one. The function is tested quite well and works for myself (emulator + phone + tablet).

Can you please try to:
- take a picture
- immediately after, go to Settings/Maintenance/Debug report, and generate a report which includes the settings and the logs.

**Comment by maverick74** [comment] 2023-05-17 10:45
Here you go:

[ntmb-debug-2023-05-17.zip](https://github.com/tfonteyn/NeverTooManyBooks/files/11497109/ntmb-debug-2023-05-17.zip)

**Comment by tfonteyn** [comment] 2023-05-17 16:05
There are no errors in the logs, and the way it's coded is using standard Android Intents.
I'll need to have a think on how to tackle this one.
For now, please take the picture while outside of the app, then import it using "Da Galeria" option.

I'll get back to you later.

**Comment by maverick74** [comment] 2023-05-17 16:56
See if this has any extra info.

here, first, i set the book profile in "edit mode" and then taken the photo... maybe it "catched" something else...

[ntmb-debug-2023-05-17-2.zip](https://github.com/tfonteyn/NeverTooManyBooks/files/11500767/ntmb-debug-2023-05-17-2.zip)

**Comment by maverick74** [comment] 2023-05-17 18:29
Forget it. I've taken a look myself.
nothing there to see...

**Comment by tfonteyn** [comment] 2023-05-18 10:28
I've double checked, but the code is so simple that it's hard to see what can go wrong.

I've created a debug build which will dump extra info to the log file. It's on my one-drive again.

[debug version on one-drive](https://1drv.ms/u/s!Aify9sSvzXtjgUQ-ZVwX5m54i4a8?e=ZkNPrI)

Important:
- it's marked as v4.3.6-beta, which has the same id as the normal release. As such it will install as an UPGRADE to your existing release. Rest assured that future versions will simply upgrade this one without any other action needed.
- Nevertheless: make a BACKUP of your data (always good advice); use the side-menu, "Copia de Seguranca", choice "Opcoes" and make sure to set "Todos os livros" before tapping the "Iniciar" button.

One thing though: I have noticed that some android devices will provide the camera screen with a button (little camera) to take the picture, and immediately/automatically return to the calling app, while other devices require tapping an extra button (a checkmark).

**Comment by maverick74** [comment] 2023-05-18 23:02
Ok. New log here :)

[ntmb-debug-2023-05-18.zip](https://github.com/tfonteyn/NeverTooManyBooks/files/11512094/ntmb-debug-2023-05-18.zip)

**Comment by tfonteyn** [comment] 2023-05-19 10:30
(notes to myself)

logs:

2023-05-18T22:57:05.537|TakePictureContract|DEBUG|createIntent|dstFile=/storage/emulated/0/Android/data/com.hardbacknutter.nevertoomanybooks/files/Pictures/tmp/CoverHandler_0.jpg|parentFile=/storage/emulated/0/Android/data/com.hardbacknutter.nevertoomanybooks/files/Pictures/tmp|parentFile.isDirectory=true|parentFile.exists=true|.
2023-05-18T22:57:05.549|TakePictureContract|DEBUG|createIntent|dstUri=content://com.hardbacknutter.nevertoomanybooks.GenericFileProvider.beta/external-path-pics/tmp/CoverHandler_0.jpg|.

2023-05-18T22:57:25.287|TakePictureContract|DEBUG|parseResult||resultCode=-1|intent=null|.
2023-05-18T22:57:25.33|TakePictureContract|DEBUG|parseResult|dstFile=/storage/emulated/0/Android/data/com.hardbacknutter.nevertoomanybooks/files/Pictures/tmp/CoverHandler_0.jpg|dstFile.exists()=true|parentFile=/storage/emulated/0/Android/data/com.hardbacknutter.nevertoomanybooks/files/Pictures/tmp|parentFile.isDirectory=true|parentFile.exists=true|.

=> dstFile.exists()=true => picture was taken + delivered to tmp dir.

prefs:
camera.image.action=1 (-> crop)
camera.image.autorotate=0

**Comment by tfonteyn** [comment] 2023-05-19 12:53
I found a potential issue in the post-processing code.
 I'm not sure it's the cause of your problem, but can you please try this new build:

[v4.5.6-beta2](https://1drv.ms/u/s!Aify9sSvzXtjgUXtUHbh2N6js70l?e=BJwpJ8)

**Comment by maverick74** [comment] 2023-05-19 13:37
> I found a potential issue in the post-processing code. I'm not sure it's the cause of your problem, but can you please try this new build:

Problem still persists.
new log
[ntmb-debug-2023-05-19.zip](https://github.com/tfonteyn/NeverTooManyBooks/files/11517383/ntmb-debug-2023-05-19.zip)

**Comment by tfonteyn** [comment] 2023-05-19 14:56
I'm fairly confident that I have now found the issue. So, here we go, a release build:

[v4.3.6](https://1drv.ms/u/s!Aify9sSvzXtjgUZkprrIWfJoNulb?e=HhdwDQ)

Once you confirm this, I'll upload this exact same file to the gihub release page.

(and if the bug is still there... I'll be really embarrassed...)

**Comment by maverick74** [comment] 2023-05-19 16:47
It's still there!!!

I'm using OpenCamera. Can it be because of that?

**Comment by tfonteyn** [comment] 2023-05-19 17:06
eeek... consider me very embarrassed now. 

    OpenCamera

It shouldn't. I suppose that might explain the "null"+OK I could see in your logs (instead of the expected "empty-intent" + OK) but I could see the file had been returned fine unless the file is not in a standard format.

Could you please double-check by using the standard camera-app?

I'll see if I can do a quick check with OpenCamera as well.

Meanwhile let me double check my build to make sure I did not simply goof-up.  Otherwise, it's back to a debug build.

**Comment by tfonteyn** [comment] 2023-05-19 17:51
I just tested OpenCamera on an Android 8.1 emulator and it worked fine.
The "null"+OK is indeed specific to OpenCamera but is not causing an issue with my fix in the 4.2.6-rc1 patch.

I'll wait for you to double-check by using the standard camera-app.

A side remark: as I understand from [android 11 about page](https://developer.android.com/about/versions/11/behavior-changes-11#media-capture) "only pre-installed system camera apps can...". I'll add this to my TODO list to explicitly support OpenCamera as a preference option. But that is obviously not the issue today as you're on 8.1 anyhow.

**Comment by maverick74** [comment] 2023-05-19 20:42
> I'll wait for you to double-check by using the standard camera-app.

No. With the standard camera it doesn't work either. I completely removed opencamera to try it

**Comment by tfonteyn** [comment] 2023-05-20 09:55
ok - I think I'm on the right track now; I seem to have reproduced the problem fully.

Here's a workaround:
Please go to Settings, scroll down to "Editar", and tap"Imagens de capa".
Now set the second option "Acção depois de tirar uma foto" to "Nenhum".

Then test again using my last upload [v4.3.6](https://1drv.ms/u/s!Aify9sSvzXtjgUZkprrIWfJoNulb?e=HhdwDQ)

That *should* work with both the native camera app and OpenCamera.

I certainly found an issue when the option was "Cortar" which I will need to investigate further.

**Comment by maverick74** [comment] 2023-05-20 10:48
> ok - I think I'm on the right track now; I seem to have reproduced the problem fully.
> 
> Here's a workaround: Please go to Settings, scroll down to "Editar", and tap"Imagens de capa". Now set the second option "Acção depois de tirar uma foto" to "Nenhum".
> 
> Then test again using my last upload [v4.3.6](https://1drv.ms/u/s!Aify9sSvzXtjgUZkprrIWfJoNulb?e=HhdwDQ)
> 
> That _should_ work with both the native camera app and OpenCamera.
> 
> I certainly found an issue when the option was "Cortar" which I will need to investigate further.

YES!!! THAT'S IT!!! IT WORKS!!! :)

**Comment by tfonteyn** [comment] 2023-05-20 16:54
good to hear :)

As you have the workaround, and can still call "crop" from the image context menu afterwards, I'm not going to release 4.3.6.
Instead I'll be doing the 4.4.0 release in the next couple of days.

This will include:
- New field to hold the original-title of a translated book (#13)
  Displayed by default, but can be hidden via Settings/Field-Visibility.
- When editing a book, the language, format, color drop-down fields
  will now show a set of defaults in addition to the users previously used values  (from #9).

As usual, I'll add a note here when done.

**Comment by maverick74** [comment] 2023-05-21 11:30
Let me ask you something a bit off-topic: ISBN is an international number system for books...

So... Why don't we get the complete info (title and author, at least)?

It finds a match for the ISBN but it never fills author nor title (in my experiences)

The software clearly works iyam, so it's not a bug. Isn't there a global open DB or something with these infos???

**Comment by tfonteyn** [comment] 2023-05-21 13:53
First general info, then at the end perhaps a solution for your question.

    Isn't there a global open DB

there used to be... and a good one: [https://isbndb.com/](https://isbndb.com/) used to have a free access plan but they disabled that plan years ago (I used to use it when I had a the precursor of NMTB as a private webserver). It's now a minimum of $14.95/month; for my free app this is a non-starter. I haven't found an alternative yet.

    Why don't we get the complete info (title and author, at least)?

It depends on which search-sites (sources) the book is found.
The app does combine information from multiple sites according to the order you list and enable them in Settings/Websites. Keep in mind that depending on your books, not all sites make sense to enable (especially the comic ones)

I should add this info to the wiki really: 
(Note I am NOT affiliated with any of these.)

Generic sites, claiming to have many books, but certainly not all:
- Google Books
- OpenLibrary

The specialized sites: these actually work the best.
- Bedetheque: French (and more) comics
- StripInfo / LastDodo: Dutch (and more) comics
- ISFDB : English (and more) books genre: science-fiction, fantasy, ... 
- KB.NL: Dutch books only

Commercial sites
- BOL.com: mostly Dutch, but also a large selection of other languages. Limited to what is available in print.
- Amazon: sigh.... they are blocking access more and more. I can't "amazon.com" from a test environment any-more as they use captchas. Same environment can access "amazon.co.uk" just fine. Other specific country sites for amazon might vary.
Unless I find a solution, I fear I will permanently have to remove Amazon.

Mentioned on the github about page: Goodreads/LibraryThing which I used to support, are now owned by Amazon (via AbeBooks) and you can guess it... they use captchas to block access.

    It finds a match for the ISBN but it never fills author nor title (in my experiences)

I looked at your prefs and see you are on the default "com" site. You should probably change that to "https://www.amazon.es"  (there is no pt site). If this does not solve the lookup issue, can you please give me an example ISBN which fails to add the Author?

I also will consider any proposal for a new website to addded/create a "SearchEngine" for, depending on language and difficulty (coincidently, see #14 + BOL was added upon a user request)

**Comment by maverick74** [comment] 2023-05-21 20:21
> If this does not solve the lookup issue, can you please give me an example ISBN which fails to add the Author?

I'm trying, as an example, Dom Quixote de la Mancha. The book I own has, as ISBN, the number 9789722057011. Interestingly, OpenLibrary's ISBNs do not match.

I suppose it is, maybe, different versions or something. (also, I've set OpenLibrary as the first source of info)

**Comment by tfonteyn** [comment] 2023-05-22 16:50
It's a "difficult" book by which I mean there are likely hundreds of editions, some with and some without ISBN (and different ISBN's).

Searching LibraryThing for example claims 9789722057011 as an english book, and gives as 2nd result the Portuguese version with the comment "This is a secondary, minority match and may be the result of ratty data."

BookFinder then lists it as the Portuguese version but stated the author as "Miguel".
I'm considering adding bookfinder.com as a source, but the amount of data they provide for a book is quite minimal.

Amazon (sigh... today I spend a couple of hours to try to fix the captcha... grrr) lists it correctly it seems, but as they block so many requests that does not help either.

By default I order OpenLibrary at the bottom of the list (and in earlier versions of the app even as disabled by default) as I found the data not to be very good/complete. But a lot depends on the type of books obviously.

Not a lot we can do about it I'm afraid (except by adding more sites).

**Comment by maverick74** [comment] 2023-05-22 17:19
> It's a "difficult" book by which I mean there are likely hundreds of editions, some with and some without ISBN (and different ISBN's).

How do i manage to have such "good" choices? i ask myself... 
like when i think about buying something!!! I always tend to like the one that's more expensive (ending without buying anything ahaha)

> Not a lot we can do about it I'm afraid (except by adding more sites).

I can suggest a few Portuguese ones... just not sure which one is actually the best.
Would have to "think about it"...

**Comment by tfonteyn** [comment] 2023-05-22 21:27
How do i manage to have such "good" choices? i ask myself...

hehe; it happens with many more books.

    ending without buying anything ahaha

I usually end up with getting the cheap copy AND the deluxe version....

    I can suggest a few Portuguese ones.

Please do. I'm happy to look at adding more sources.

**Comment by maverick74** [comment] 2023-05-23 16:34
> Please do. I'm happy to look at adding more sources.

Seems like wook.pt would be a good one, if there's a way to bypass cloudflare (I think...)

If not we can try others...

**Comment by tfonteyn** [comment] 2023-05-23 16:42
sorry for the bad news, but a quick check with wget shows it is likely to be very-difficult or impossible.
Based on the time I already spend on Amazon... I'm not going to try another one of those blockers :(

$ wget wook.pt
--2023-05-23 17:37:16--  http://wook.pt/
Resolving wook.pt (wook.pt)... 141.101.90.98, 141.101.90.97, 141.101.90.96, ...
Connecting to wook.pt (wook.pt)|141.101.90.98|:80... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-05-23 17:37:16 ERROR 403: Forbidden.

$ wget https://wook.pt
--2023-05-23 17:37:31--  https://wook.pt/
Resolving wook.pt (wook.pt)... 141.101.90.98, 141.101.90.97, 141.101.90.96, ...
Connecting to wook.pt (wook.pt)|141.101.90.98|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-05-23 17:37:31 ERROR 403: Forbidden.

$ wget https://www.wook.pt
--2023-05-23 17:37:37--  https://www.wook.pt/
Resolving www.wook.pt (www.wook.pt)... 141.101.90.97, 141.101.90.99, 141.101.90.98, ...
Connecting to www.wook.pt (www.wook.pt)|141.101.90.97|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-05-23 17:37:38 ERROR 403: Forbidden.

**Comment by maverick74** [comment] 2023-05-23 18:36
I suppose Bertrand.pt also suffers the same problem... Can you please check?

**Comment by tfonteyn** [comment] 2023-05-25 09:52
Bertrand.pt

Bertrand.pt does not block immediately (like wook did), so I can take a look.

But would you mind opening a new Issue please?  It's easier to reference.

**Comment by maverick74** [comment] 2023-05-25 11:13
> But would you mind opening a new Issue please? It's easier to reference.

Done: #15 

Still it's funny that it works for bertrand and not for wook, because bertrand owns Wook.pt 
(while bertrand, itself, is owned by portoeditora.pt)

Curiosity: bertrand is the world's oldest bookshop still in activity: [Livraria Bertrand - Wikipedia](https://en.wikipedia.org/wiki/Livraria_Bertrand)

About this bug, i think it can be closed... or do you have more "to-do"'s related to it?

**Comment by tfonteyn** [comment] 2023-05-25 14:03
okido - cheers.

    oldest bookshop
sweet :)

    can be closed
no; it's fixed in the upcoming 4.4.0 (together with partial OpenCamera support) and the workaround is easy anyhow.

**Closed as completed by tfonteyn** 2023-05-25 14:03 UTC
Labels: bug
