### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by shadows-word** [tfonteyn/NeverTooManyBooks#2] opened 2023-01-28 19:46 UTC
Hi!
I can't import my books. I tried importing from Book Catalogue backup, from .CSV and also from json. I always get the message that an unknown error occurred.

**Comment by tfonteyn** [comment] 2023-01-28 21:48
Hi,

>Book Catalogue backup
I presume you mean the older program I forked from?

Easiest would be if you attached your old backup file here, and I'm happy to take a look in detail.
I've not tested in a long time to import BC backups - no reason they should not work (apart from the styles)
If you prefer not to do that, can you  instead attach perhaps the first 10 lines of your CSV file ?

Please also try to do an import, see it fail, then get into "Settings", scroll down to the bottom and choose "maintenance"... then "bug report". Just check the "log files" + "settings" and click "ok"... it will ask to email.
My apologies, but I still have not setup a dedicated email. So just grab the attachments + the info-text and post them here.

**Comment by shadows-word** [comment] 2023-01-31 21:19
Yes, I mean that older program.

I have to correct my statement about the error message.
When I try to import a .bcbk-file, I get the message "The selected file is not recognized" before I can choose what to import (new books only etc.)
When I try to import a CSV file, I get the message "Nothing selected" after tapping on "Start import".
When I try to import a json file, I get the message "An unexpected error occurred" before I can choose what to import..

I have attached the bcbk file (had to do a backup without the cover pictures, bc the file would have been to large to attach) and a csv with the first 10 lines.

The bug report only contains the preferences and no log file. The info text:

App: com.hardbacknutter.nevertoomanybooks
Version: 3.4.1 (23, 2022-11-27T15:22:03.8878958)
SDK: 10 (29 release-keys)
Model: SHIFT6mq
Manufacturer: SHIFT
Device: axolotl
Product: axolotl
Brand: SHIFT
Build: QSV1.210329.038
Signed-By: Not signed, likely development version

logScreenParams|

configuration:
screenWidthDp=411
screenHeightDp=782
orientation=PORTRAIT
densityDpi=420
metrics:
widthPixels=1080
heightPixels=2118
density=2.625


[shadowsword_bcbk.tar.gz](https://github.com/tfonteyn/NeverTooManyBooks/files/10551119/shadowsword_bcbk.tar.gz)
[preferences.txt](https://github.com/tfonteyn/NeverTooManyBooks/files/10551016/preferences.txt)
[to-import.csv](https://github.com/tfonteyn/NeverTooManyBooks/files/10551017/to-import.csv)

**Comment by tfonteyn** [comment] 2023-01-31 23:42
Hello,

Thanks for that - made it very easy.

It wasn't to unexpected or bad.
- I had removed the BC import format. Simply restoring the code that handled it was quick and took care of that obstacle.
- The Csv import was a small bug and also easy to fix.
- Json: yes, that would be expected - not a bug, but I should put up a nicer message. The json format is specific to NeverTooManyBooks and is used in the new backup format. You can ignore it.

So right now I can successfully import the bcbk file as well as the csv file.

There are warnings about 8 or so books that fail - I'll take another look tomorrow. Probably some bad data which should be easy to fix.

I was in fact getting NeverTooManyBooks 4.0 ready for release soon. I want to do some more testing, but I'm happy to upload a beta which has the fixes for the BC import already put in.

I'll do that tomorrow, and let you know.

btw, my german is not 100%, if you have any feedback on the german UI text, that would be wonderful.

**Comment by tfonteyn** [comment] 2023-02-01 16:20
warnings about 8 or so books that fail
bad data indeed, to be specific duplicate author names which were only different with a "." at the end of the name.
I added extra filtering so the app can handle those as well now.

All in all, I'm very happy with your "problems" as they showed a couple of issues that needed fixing.

I've run out of time today, and want to do some extra tests so the beta upload will be for tomorrow instead.

**Comment by tfonteyn** [comment] 2023-02-02 10:41
Good morning,

As promised:  [v4.0.0-beta1](https://github.com/tfonteyn/NeverTooManyBooks/releases/tag/v4.0.0-beta1)

This includes fixes for the issues you hit.

You do need to do a simple conversion:

The "bcbk"  (which is a "tar" archive) backup file needs to be converted to a "zip" file. 
Just use any app which can open tar files and save zip files. I use 7z.
When zipping, make sure the "INFO.xml", "books.csv" and all cover files are at the top level
of the "zip" file.

**Comment by shadows-word** [comment] 2023-02-02 21:28
Worked like a charm, thank you.

I'm glad, that I could show you some issues :)

I'll look into the german UI text, but I can't promise how soon I will be able to spend a decent amount of time.

**Comment by tfonteyn** [comment] 2023-02-03 18:45
don't worry about it.

Closing this issue now, but please log any new issues you see.

**Closed as completed by tfonteyn** 2023-02-03 18:45 UTC

**Comment by tfonteyn** [comment] 2023-02-08 12:02
[v4.0.0](https://github.com/tfonteyn/NeverTooManyBooks/releases/tag/v4.0.0) is now released

No further fixes, but some small features added since the beta.
