### ISSUE TITLE
App Freezes Upon list price with .

### ISSUE THREAD

**Issue by florisre** [tfonteyn/NeverTooManyBooks#4] opened 2023-03-26 19:16 UTC
Language: German

for the book with the ISBN 3518366823, the app fetches a listed price of 7.0

This formatting makes the app freeze, since the field is expecting 7,0

**Comment by tfonteyn** [comment] 2023-03-26 21:23
Hi,

Please confirm you are on version 4.0 ? This fixed a problem exactly as you are describing.
(if upgrading, 4.1 is now out as well)

Can you please create a debug-report and upload it here? Go to Settings, then at the bottom "maintenance / Instandhaltung"
and then "bug report / Fehlerbericht". Make sure to include the log files and the database.

You can also try these:

1. Can you confirm that the book was saved? If it was - use the settings screen to temporarily switch the UI to English; edit the book removing the list price + save it ;- Afterwards witch the UI back to "system default" (or german).

2. Switch off fetching data from Amazon. When you're on the ISBN search-screen, select the website icon in the taskbar and deselect Amazon. I presume you will have Google,ISFDB,OpenLibrary enable which is normally enough for all common types of books.
For completeness sake: stripinfo/lastdodo/bedetheque is for comics; KBNL is specificaly dutch books ... so you won't need any of those I presume.

**Comment by florisre** [comment] 2023-03-26 22:07
I am running 4.1, [debug report](https://github.com/tfonteyn/NeverTooManyBooks/files/11073184/ntmb-debug-2023-03-27.zip) is attached.

1 does not work, the app freezes when trying to save without actually saving the book.

2 solves the issue indeed

**Comment by tfonteyn** [comment] 2023-03-26 22:13
1. ok - I saw the issue in the logs - thanks for those. I should be able to fix that and get a new version out.

2. it's just a workaround for now of course.

To late at night now - but I'll get back to you soon.

**Comment by tfonteyn** [comment] 2023-03-27 16:03
Hi,

You say it hangs when you're saving the book (from the edit-page).
Firstly, the error I saw in the logs last night was misleading - it's really just a warning and I'm not sure it has anything to do with the issue.

I've tried to reproduce with the ISBN you provided, but it is all working (in german and english) - the amazon parser in fact is not even finding any price information (they seem to have changed their pages *again*).

Can you please do a test:

1. make sure to enable *only* Amazon, Google and OpenLibrary.
2. use the same ISBN and do a search
3. Q: I presume the edit-screen with the main details opens - correct?
4. Make a screenshot of that page and upload it here.
5. Q: when you switch to publication (Veröffentlichung) tab, does it display ? And what exactly (if anything) is filled in the price-listed field (value and currency) ?
6. Make a screenshot of that page and upload it here.
7. If there was anything in those fields, clear the value field by tapping the little delete-icon.
8. Tap the save-icon on the taskbar - if it hangs again, kill the app; then start it and create a new debug report without doing anything else.

I'll try some more things here, and if the above or my own tests show nothing I'll create a custom debug for you.

**Comment by florisre** [comment] 2023-03-27 19:43
Everything works fine with only these sources enabled. No price information is loaded.

Adding ISFDB gets the price information.
7. does not work, tapping the little delete icon leads to the app freezing, before that it looks like this.
![.](https://user-images.githubusercontent.com/47896527/228048713-d46ce2bc-ae1b-4a8f-82cb-c4666bb5f550.png)

[This](https://github.com/tfonteyn/NeverTooManyBooks/files/11082414/ntmb-debug-2023-03-27.1.zip)
 is the debug report. Note that the app also freezes when selecting "database" while creating a debug report – should probably be a separate issue.

**Comment by tfonteyn** [comment] 2023-03-27 22:42
The selecting "database" issue... yes, quite a silly bug  that slipped in when I refactored that code a while ago. Fixed now. Thanks for finding it :)

The "7.0" from the screenshot. Ok, I can partially reproduce: I can trace what is happening and why you see the hang. Preventing that part is easy if I add some defensive code but that would just be a workaround.
What I haven't found yet is the root cause.
As far as I can tell, in your case the price is parsed, but then end up being passed on as a string (this was as designed) with the wrong decimal separator (this is the bug). I'm looking into preventing this from happening at all.
My issue is that even running a device fully in german, I still get that price parsed just fine.

I'll try to check further tomorrow... but I'm a bit busy tomorrow... might be Wednesday.

**Comment by tfonteyn** [comment] 2023-03-29 12:54
Hi,

I have not been able to reproduce, but have partially 'faked' the problem. Based on that I've uploaded a new beta: [v4.1.1-beta1](https://github.com/tfonteyn/NeverTooManyBooks/releases/tag/v4.1.1-beta1)

Can you please upgrade. It won't affect your data, and let me know if that same ISBN is working now.
I mean: 1. No hangs? + 2. the price is correctly set to  DM 7

thanks

**Comment by florisre** [comment] 2023-03-30 07:10
Can confirm both 1 and 2. Thanks a lot for your time & effort!

**Closed as completed** 2023-03-30 07:10 UTC
