### ISSUE TITLE
Dates

### ISSUE THREAD

**Issue by eafranca** [tfonteyn/NeverTooManyBooks#72] opened 2024-06-19 15:36 UTC
When I mark the reading start date or acquisition date, the app inserts the date before the selected one.
When I set the end date (any), it puts the current date.
The app only displays the correct reading completion date when I mark "read".

**Comment by tfonteyn** [comment] 2024-06-19 16:03
I'll need some more details on this one.

Typical usage is:
- either on the list or the book details screen (NOT in edit mode), use the "read" option and the book will be marked "read" and the end-date will be 'today'
- In edit-mode for a book:
  - use the 'read' status button and the behaviour is as above.
  - use the "read-start" to select any date; this does not affect the end-date or the status
  - use the "read-end" date and a dialog for BOTH dates, i.e. you need to select the range start->finish + the status is set to 'read'.

Please let me know the steps you take in detail. Perhaps there is another/better way then what I describe here, always happy to check.

**Comment by tfonteyn** [comment] 2024-07-06 17:03
I didn't hear back from you. If the above information is not working and/or you have more questions, then feel free to reopen this issue or log a new one.

**Comment by ahrmn** [comment] 2024-07-11 19:54
@tfonteyn I have the same Issue

> use the "read-end" date and a dialog for BOTH dates, i.e. you need to select the range start->finish + the status is set to 'read'.

I consider this non-intiutive (when I click on read-end I want to enter only the end date, I entered the start date earlier since it's earlier in the menu), but if it would work like this it would be fine. 

However the actual behaviour is for me:
I mark the range from date X to y and save. The book shows today as end date.
If I manually edit the end date (as string) it also sets today as end date.

I use the German locale, maybe that's a problem?
I attached a screen recording of my usage.

https://github.com/user-attachments/assets/8d9a4856-1d18-4b3f-942d-cb98e3974c92

**Comment by tfonteyn** [comment] 2024-07-11 20:42
reopening.

> I consider this non-intiutive

You may have a point indeed.

> manually edit the end date (as string) it also sets today as end date.

bit late now today, but I'll check this tomorrow and get back to you

**Comment by tfonteyn** [comment] 2024-07-12 09:53
> manually edit the end date (as string) it also sets today as end date.

It's a bug - I reproduced; it always happens when editing the range (manual, or picked).

I've found the issue and it's a simple fix.

I'll let you know if it will be released in a 6.1.4 or in the upcoming 6.2.0 release.

**Comment by ahrmn** [comment] 2024-07-12 11:46
Awesome, I am glad it was a simple fix.

**Comment by tfonteyn** [comment] 2024-07-15 13:24
A quick update to let you know what's happening.
This issue has been fixed and will be available in the upcoming 6.2 release.
But I'm still working on a small number of other enhancements/fixes which I also want in 6.2.
If things go as planned, you can expect 6.2 by next weekend.

**Comment by tfonteyn** [comment] 2024-07-18 13:40
and here you go [6.2.0](https://github.com/tfonteyn/NeverTooManyBooks/releases/download/v6.2.0/NeverTooManyBooks-6.2.0.apk)

**Closed as completed by tfonteyn** 2024-07-18 13:40 UTC
Labels: bug
