### ISSUE TITLE
[bug] Crash when editing a cover image

### ISSUE THREAD

**Issue by coastgnu** [tfonteyn/NeverTooManyBooks#68] opened 2024-06-18 07:59 UTC
Long press a cover image of an existing book, (Raus aus der AUTOkratie - rein in die Mobilität von morgen!:which comes with a wrong title image), 'Replace',  'From Camera's,  results in an immediate crash

[ntmb-crash-2024-06-18T09_51_05.942968.txt](https://github.com/user-attachments/files/15882343/ntmb-crash-2024-06-18T09_51_05.942968.txt)

**Comment by tfonteyn** [comment] 2024-06-18 08:13
java.lang.IllegalArgumentException: Failed to find configured root that contains \/storage\/9C33-6BBD\/Android\/data\/com.hardbacknutter.nevertoomanybooks\/files\/Pictures\/tmp\/31013899522958.jpg
at androidx.core.content.FileProvider$SimplePathStrategy.getUriForFile(Unknown Source:867)at androidx.core.content.FileProvider.getUriForFile(Unknown Source:467)at f0.FileProvider.getUriForFile(Unknown Source:0)
at com.hardbacknutter.nevertoomanybooks.utils.GenericFileProvider.createUri(Unknown Source:92)at com.hardbacknutter.nevertoomanybooks.activityresultcontracts.EditPictureContract.createIntent(Unknown Source:63)at com.hardbacknutter.nevertoomanybooks.activityresultcontracts.EditPictureContract.createIntent(Unknown Source:46)

**Comment by tfonteyn** [comment] 2024-06-18 08:55
ok - certainly a problem in my code.

For now, you can disable the auto-edit in Settings, scroll down to "Edit" and tap "Cover Images".

Set the second option "Action after taking a picture" to "None"

At least that should stop the crash for now.

More later.

**Comment by tfonteyn** [comment] 2024-06-18 09:26
"good news" .... ahum;  I can now reproduce this issue. It's a permissions issue, but not due to anything you did or did not do. I'll need to investigate this further.

Warning: when using the "Storage Volume" option, after the initial dialog, i.e. in the second dialog, choosing whether to simply "set" or to "move": when immediately tapping "ok", the action will always be "set" regardless that "move" is checked. Solution: tap "set", then tap "move" before "ok".

There is no need to do the above right now, I just want to mention it in case you are trying things out.
This is/will obviously also be fixed.

**Comment by tfonteyn** [comment] 2024-06-18 12:10
turns out it's Google bug [37125252](https://issuetracker.google.com/issues/37125252) or in more correct terms, a Google total lack of planning/understanding their own API's. And they seem to have closed it without even bothering to understand/fix it. Sigh... on the other hand, I **should** have run into this issue before as it's pretty fundamental - not sure why I never did.

I created a fix for this issue, but I want to test it on a number of different Android versions first. I'll try to upload a new release later today, the latest tomorrow.

**Comment by tfonteyn** [comment] 2024-06-18 17:11
and here you go [6.1.2](https://github.com/tfonteyn/NeverTooManyBooks/releases/download/v6.1.2/NeverTooManyBooks-6.1.2.apk)

**Closed as completed** 2024-06-18 17:11 UTC
